# Generated by Django 6.0.3 on 2026-03-13 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('user', 'name')},
        ),
    ]
